# Generated by Django 4.2.1 on 2024-04-26 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('weight', models.CharField(max_length=50, null=True)),
                ('initial', models.CharField(max_length=45)),
                ('first_quarter_plan', models.CharField(max_length=45)),
                ('second_quarter_plan', models.CharField(max_length=45)),
                ('third_quarter_plan', models.CharField(max_length=45)),
                ('fourth_quarter_plan', models.CharField(max_length=45)),
                ('first_quarter_performance', models.CharField(blank=True, max_length=45, null=True)),
                ('second_quarter_performance', models.CharField(blank=True, max_length=45, null=True)),
                ('third_quarter_performance', models.CharField(blank=True, max_length=45, null=True)),
                ('fourth_quarter_performance', models.CharField(blank=True, max_length=45, null=True)),
                ('performance_in_percent', models.CharField(blank=True, max_length=45, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('is_approved', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=45)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('weight', models.CharField(max_length=50, null=True)),
                ('status', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_approved', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=45)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StrategicGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('weight', models.IntegerField(max_length=50, null=True)),
                ('assigned', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
