# Generated by Django 4.2.1 on 2024-04-26 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planApp', '0001_initial'),
        ('reportApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicgoal',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_strategic_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategicgoal',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_strategic_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategicgoal',
            name='sector_id',
            field=models.ManyToManyField(blank=True, null=True, to='userApp.sector'),
        ),
        migrations.AddField(
            model_name='strategicgoal',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_strategic_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maingoal',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_main_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maingoal',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maingoal',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_main_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maingoal',
            name='division_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userApp.division'),
        ),
        migrations.AddField(
            model_name='maingoal',
            name='monitoring_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userApp.monitoring'),
        ),
        migrations.AddField(
            model_name='maingoal',
            name='sector_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userApp.sector'),
        ),
        migrations.AddField(
            model_name='maingoal',
            name='strategic_goal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planApp.strategicgoal'),
        ),
        migrations.AddField(
            model_name='maingoal',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_main_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kpi',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_kpis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kpi',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kpi',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_kpis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kpi',
            name='division_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userApp.division'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='main_goal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planApp.maingoal'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='measure_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportApp.measure'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='monitoring_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userApp.monitoring'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='sector_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userApp.sector'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_kpis', to=settings.AUTH_USER_MODEL),
        ),
    ]
