# Generated by Django 4.2.1 on 2024-04-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
        ('planApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategicgoal',
            name='sector_id',
            field=models.ManyToManyField(to='userApp.sector'),
        ),
        migrations.AlterField(
            model_name='strategicgoal',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=50, null=True),
        ),
    ]
