# Generated by Django 5.0.4 on 2024-05-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planApp', '0003_alter_strategicgoal_sector_id_and_more'),
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maingoal',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategicgoal',
            name='sector_id',
            field=models.ManyToManyField(blank=True, null=True, to='userApp.sector'),
        ),
        migrations.AlterField(
            model_name='strategicgoal',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
