# Generated by Django 4.2.1 on 2024-04-26 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reportApp', '0001_initial'),
        ('userApp', '0001_initial'),
        ('planApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='division_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_summary', to='userApp.division'),
        ),
        migrations.AddField(
            model_name='summary',
            name='monitoring_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_summary', to='userApp.monitoring'),
        ),
        migrations.AddField(
            model_name='summary',
            name='sector_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector_summary', to='userApp.sector'),
        ),
        migrations.AddField(
            model_name='kpidescription',
            name='kpi_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpidescription', to='planApp.kpi'),
        ),
    ]
