# Generated by Django 4.2.1 on 2024-05-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
    ]
